#!/bin/bash

MFLAG=/var/lib/maxscale/maintenance

exec {lock_fd}>/var/lock/maxscale-restart || exit 1
flock -n "$lock_fd" || { echo "ERROR: This script is already running." >&2; exit 1; }
touch $MFLAG
monit unmonitor all
maxscale-stop
maxscale-start
monit monitor all
rm -f $MFLAG
flock -u "$lock_fd"
