#!/bin/bash

# Start MaxScale
echo 'Starting...'
rm -f /var/run/maxscale/maxscale.pid
rm -f /var/cache/maxscale/maxscale.lock
rm -f /var/lib/maxscale/maxscale.lock
maxscale -U maxscale &
echo "MaxScale PID = $!"
exit 0
