#!/bin/bash

# Stop MaxScale
echo 'Stopping...'

PID=$(pgrep -x 'maxscale')
if [[ ! -z $PID ]]; then
    echo 'Sending SIGTERM'
    kill $PID 2> /dev/null
    PID=$(pgrep -x 'maxscale')
    if [[ ! -z $PID ]]; then
        echo 'Sending SIGKILL'
        kill -9 $PID 2> /dev/null
    fi
fi

exit 0
